[default]
extend-ignore-re = [
    # Git SHA fragments in comments.
    "[0-9a-f]{7,40}",
]

[default.extend-words]
consts = "consts"

[files]
extend-exclude = ["**/*.js", "**/*.css", "**/*.html", "examples/*/static/**/*.*"]
